.travis.yml, app/assets/stylesheets/incidents.scss, app/assets/stylesheets/layout.scss, app/views/incidents/_form.html.haml, app/views/users/index.haml, coverage/.last_run.json, test/application_system_test_case.rb, test/system/deactivating_employees_test.rb, test/system/deleting_user_test.rb, test/system/managing_users_test.rb
Even more checks will cause builds to fail if they don't pass. The only ones that I needed to fix were contrast issues, again with Rails-native stuff.
My suspicion is that some checks aren't being triggered because Capybara isn't interacting with potentially offending elements. Perhaps it might be nice to make more assertions about what kind of content should be on each page, thereby causing those checks to run on those selectors.
=> More accessibility checks

app/views/incidents/_table.haml
=> Anyone can print at any time

app/controllers/application_controller.rb, app/controllers/incidents_controller.rb, app/models/incident.rb, app/views/incidents/_table.haml, app/views/incidents/edit.html.haml, app/views/incidents/unclaimed.haml, app/views/layouts/_navbar.haml, config/routes.rb
Closes #53.
Removes the ability for drivers to select supervisors.
Adds the ability for supervisors to 'claim' incidents as their own.
=> Drivers can't select supervisors

app/controllers/application_controller.rb, app/controllers/incidents_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/division.rb, app/models/divisions_user.rb, app/models/incident.rb, app/models/user.rb, app/views/incidents/_division_filters.haml, app/views/incidents/_table.haml, app/views/incidents/by_date.haml, app/views/incidents/new.html.haml, app/views/users/_form.haml, app/views/users/index.haml, db/migrate/20171214202906_create_divisions.rb, db/migrate/20171214203943_add_division_id_to_users.rb, db/migrate/20171215150218_create_divisions_users.rb, db/migrate/20171215151312_add_uniqueness_index_to_divisions_users.rb, db/schema.rb, db/seeds.rb, lib/tasks/divisions.rake, spec/factories/divisions.rb, spec/factories/users.rb
Closes #67.
Drivers:
+ No changes.
Supervisors:
+ Can only select drivers in their division(s) when creating a new incident.
Staff:
+ Can only select drivers in their division(s) when creating a new incident.
+ Can only see incidents in their division(s).
If needed, staff can edit themselves to be in multiple divisions. This isn't really about access control (for staff), more about ease of use.
Editing a user's divisions:
A user in multiple divisions:
A supervisor selecting drivers from only one division:
=> Restrict staff to their division(s)

app/helpers/supervisor_reports_helper.rb, app/views/incident_reports/_show.haml, app/views/supervisor_reports/_form.haml, app/views/supervisor_reports/_show.haml, config/locales/en.yml
Closes #70.
Also adds a nice way of using them in the views, which is what should be reviewed.
Before:
After:
=> Supervisor report locale entries

app/controllers/incidents_controller.rb, app/models/incident.rb, app/models/reason_code.rb, app/models/supplementary_reason_code.rb, app/views/incidents/_form.haml, app/views/incidents/_incident.xml.haml, app/views/incidents/show.html.haml, coverage/.last_run.json, db/migrate/20180911000806_create_supplementary_reason_codes.rb, db/migrate/20180911000832_add_supplementary_reason_code_id_to_incidents.rb, db/schema.rb, lib/tasks/supplementary_reason_codes.rake, spec/factories/incidents.rb, spec/factories/supplementary_reason_codes.rb, spec/system/staff/editing_incident_details_spec.rb
Closes #139.
1. Merge / deploy / migrate
2. `rake supplementary_reason_codes:create && rake supplementary_reason_codes:migrate`
3. Create a migration removing the disused column.
=> Supplementary reason codes

app/models/supplementary_reason_code.rb
so calling SupplementaryReasonCode.all would return not only all of those,
but all ReasonCode(s) also, which is not desirable. Wetness here is preferable.
=> subclasses inherit tables by default,

.gitignore, app/models/incident.rb
Requested by @sherson.
Allows us to parallel test the XML approach while keeping the existing integration intact.
Definitely open to suggestions on more sophisticated methods.
=> Export claims XML for parallel testing

spec/spec_helper.rb
This will help with #216. Now things like `.sample` will always return the same value for the same rspec seed, which means you should be able to reproduce an occasional failure.
=> Seed kernel with rspec's seed

app/views/incident_reports/_form.html.haml
Closes #205 
I have updated the button wording to say, 'Save Report and Preview PDF' and added an attribute that opens up a dialog box on submit.
=> Added a popup menu on submit and reworded the button

coverage/.last_run.json, spec/spec_helper.rb, spec/system/drivers/creating_incidents_spec.rb, spec/system/drivers/editing_incidents_spec.rb, spec/system/drivers/special_incident_fields_spec.rb, spec/system/staff/adding_users_spec.rb, spec/system/staff/deleting_incidents_spec.rb, spec/system/staff/deleting_users_spec.rb, spec/system/staff/editing_incident_details_spec.rb, spec/system/supervisors/claiming_incidents_spec.rb, spec/system/supervisors/editing_incidents_spec.rb, spec/system/supervisors/editing_supervisor_reports_spec.rb, spec/system/supervisors/special_supervisor_report_fields_spec.rb
The referenced blog post was from 2016 and since then Capybara has gotten way better at knowing to wait. As long as you use `.find` and the Capybara matchers like `have_text`, `have_selector`, etc. it should be fine.
I also swapped-in `accept_alert` which  waits for the alert to appear.
=> Removed `wait_for_ajax!`

coverage/.last_run.json, spec/support/downloads.rb, spec/system/drivers/editing_incidents_spec.rb
Both failures were time-based; and seemed to result from the followingsequence:
1. `visit` a page, do stuff
2. Click a button that produces a PDF
3. `visit` another page
4. Make assertions about the second page
When the tests would fail, the page contents would still be those of the first `visit`ed page. I think what was hapening was, if the second `visit` was called while the PDF download was still in progress, it just didn't do anything (?).
Anyways, these two test now reliably pass.
=> Found some occasional test failures, maybe fixed

app/models/incident.rb, app/views/incidents/new.html.haml, config/locales/en.yml, coverage/.last_run.json, spec/spec_helper.rb, spec/system/staff/creating_incidents_spec.rb, spec/system/supervisors/creating_incidents_spec.rb
I made it so that the supervisor who is creating the incident now has to input the time when the incident occurred.
=> Creating incidents as a supervisor 

config/deploy.rb, config/deploy/production.rb
Rather than the SSH one. It's a public repo, why introduce the complexity of agent forwarding to the process?
=> Use the https address for the repo

app/views/layouts/application.html.haml
This, it turns out was a thing Google changed sometime pretty close to when #316 was reported. Hence, why I was pretty sure that I had gotten it to work in the past.
Before approximately June, 2021, the GMaps JS would look at the nonce value on it's own `<script>` tag and add that value to all the other `<script>` and `<style>` tags that it inserts.  After then, they decided that, because the nonce for JS and the nonce for CSS can be different, it should use the nonce value from some other style tag for its own `<style>` tags.
Closes #316, and for some reason appears to close #315
=> Add nonce value to stylesheet tags

.haml-lint.yml, .rubocop.yml, Gemfile, Gemfile.lock
Added those linting gems and modified the `.rubocop.yml` to be consistent with round-three.
=> Add rubocop plugins and haml-lint

config/initializers/content_security_policy.rb
Google Maps, apparently, makes outgoing connections to itself. So, that needs to be allowed too see:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src
I don't know that this is causing any actual issues, but @sherson noticed that it was being blocked while troubleshooting our Maps API key. Closes #336
=> Add maps domain to CSP `connect-src`

app/views/incidents/show.pdf.prawn
We allow blank true for `test_status`.
https://github.com/umts/incidents/blob/a211f42e26ef01d10a1d5362a7fdb487e871ab4b/app/models/supervisor_report.rb#L21
So we have to `.present?` when checking for string presence.
=> Check `SuperVisorReport.test_status` string presence in PDF

Gemfile, Gemfile.lock
Slowly moving to resolving the problems caused by the removal of default gems.
=> Update to mail 2.8.0.rc1

Gemfile.lock
Turns out I was wrong in #357, the update to openssl _did_ break something (net-ssh).
=> Update SSH gems

Gemfile.lock
Look, Dependabot, just because I haven't merged your major version bump to Sidekiq that only fixes a vulnerability in the metrics page we don't use, doesn't mean I don't want any other updates.
=> Upgrade puma to 6.3.1

config/environments/production.rb
The prefix ends up getting prepended to the queue names, and jobs get inserted into Redis with a queue name of e.g. `incidents_production_default`. Meanwhile, sidekiq is trundling along watching a queue named `default` and no jobs ever get processed. Turns out sidekiq has been broken in production since 2021 when we last did a Rails upgrade.
The author of Sidekiq thinks this setting [is a bad idea](https://github.com/sidekiq/sidekiq/issues/4034#issuecomment-442988685).
=> Don't prefix queues with app name/environment

config/environments/production.rb
Interestingly, mail.pvtaapps.com is _also_ skylark for mail handling purposes. But it has started waiting 5 seconds to say `HELO`, which was the "actual" problem. May as well use the recommended host, though, and using SMTP over TLS it answers immediately.
=> Fix up the production mail server settings

Gemfile, Gemfile.lock
We only use it for sending emails, and we have sent at least one in production with no deprecation warnings. I Think this is now OK
Redis on the incidents server has already been updated to 7.2.
=> Update Sidekiq to 7.x

Gemfile.lock
Eliminates a warning introduced in Ruby 3.2 - something about not defining or undefining `alloc` functions in C extensions?
=> Update mysql2 to 0.5.5

.gitignore, config/boot.rb, config/deploy.rb, lib/capistrano/tasks/bootsnap.rake
Having Bootsnap enabled in production without setting anything up to periodically clear the cache means that the cache just grows forever.
=> Add bootsnap precompile step to deploy process

spec/spec_helper.rb
An alternative tack to #482, this PR makes downloads _work_ again.
It turns out that not only did we have some expectations on the files downloaded, we also were looking at the "`page`" in some cases to assert the lack of an error page and that was breaking when the page was actually the Chrome PDF viewer.
=> Try even harder to get Chrome to download PDFs
