umts/incidents

- app/controllers/users_controller.rb
- coverage/.last_run.json
Resolves a CodeClimate issue and tests #7.
> Remove some duplicated UsersController code

- .rubocop.yml
- .travis.yml
- app/assets/javascripts/incidents/edit.coffee
- app/controllers/incidents_controller.rb
- app/models/incident.rb
- app/views/incidents/_form.html.haml
- app/views/incidents/_table.haml
- app/views/incidents/show.html.haml
- coverage/.last_run.json
- db/migrate/20170523144952_drop_incidents.rb
- db/migrate/20170523145129_create_incidents_anew.rb
- db/migrate/20170525154732_add_passengers_injured_to_incidents.rb
- db/migrate/20170525155520_support_single_injured_passenger.rb
- db/migrate/20170525160451_set_incident_boolean_defaults.rb
- db/migrate/20170525173157_add_badge_number_to_user.rb
- db/schema.rb
- db/seeds.rb
- test/factories/incidents.rb
- test/factories/staff_reviews.rb
- test/factories/users.rb
- test/system/completing_incidents_test.rb
- test/system/edit_incident_test.rb
- test/system/new_incident_test.rb
- test/system/view_incident_test.rb
> Emulate SATCo form

- app/views/incidents/_form.haml
> Can add claim number

- app/controllers/users_controller.rb
- app/views/layouts/_navbar.haml
- app/views/users/_form.haml
- app/views/users/new.haml
- config/routes.rb
Closes #51.
Navbar button:
Form:
Form with an error:
Successful save:
> Add new users

- app/controllers/users_controller.rb
- app/models/user.rb
> Deactivate users who aren't in the XML

- app/assets/stylesheets/incidents.scss
- app/models/incident.rb
- app/views/incidents/edit.html.haml
> Notify supervisor on report initialization

- app/models/incident.rb
> Required occurred_at, and set to be now

- app/assets/javascripts/incident_reports/edit.coffee
- app/views/incidents/show.pdf.prawn
- app/views/supervisor_reports/_form.haml
- app/views/supervisor_reports/_show.haml
- config/locales/en.yml
- db/migrate/20171212171804_remove_hard_drive_fields_from_supervisor_reports.rb
- db/schema.rb
> Remove hard drive fields

- app/controllers/incident_reports_controller.rb
> Redirect drivers to the PDF after completing a report

- app/controllers/incidents_controller.rb
- app/controllers/users_controller.rb
- app/models/incident.rb
- app/models/incident_report.rb
- app/views/incident_reports/_form.html.haml
- app/views/incident_reports/_show.haml
- app/views/incidents/_form.haml
- app/views/incidents/show.pdf.prawn
- app/views/incidents/show.xml.haml
- db/migrate/20171213165648_move_occurred_at_to_incident_reports.rb
- db/schema.rb
This is on the way to #43, but is big enough that I wanted it to be reviewed separately.
> Required fields

- app/models/incident_report.rb
- app/views/incident_reports/_form.html.haml
> Town is a dropdown list

- app/controllers/incident_reports_controller.rb
- app/controllers/incidents_controller.rb
- app/controllers/supervisor_reports_controller.rb
- app/models/incident_report.rb
- app/views/incident_reports/edit.haml
- app/views/incidents/edit.html.haml
- app/views/supervisor_reports/edit.haml
Closes #43. Closes #57.
Required fields:
Staff view of editing an incident:
Supervisor view of editing an incident:
> Required fields, and form separation

- app/assets/stylesheets/incidents.scss
- app/views/incident_reports/_form.html.haml
> Placeholders

- config/initializers/cookies_serializer.rb
Pending deploy this Sunday, 1/28, at 9pm. This will result in all users with an active session being logged out.
> Scope cookie name to Rails environment

- app/controllers/incidents_controller.rb
- app/models/incident.rb
- app/models/incident_report.rb
- app/views/incidents/_add_supervisor.haml
- app/views/incidents/_form.haml
- app/views/incidents/_table.haml
- app/views/incidents/edit.html.haml
- config/environments/test.rb
- coverage/.last_run.json
- spec/system/staff/reviewing_incidents_spec.rb
> Remove supervisor

- app/models/incident_report.rb
- app/views/incident_reports/_form.html.haml
- coverage/.last_run.json
- spec/spec_helper.rb
- spec/system/drivers/creating_incidents_spec.rb
Closes #113.
Pending Jamin's approval.
> Remove occurred_at

- app/controllers/incident_reports_controller.rb
- app/controllers/incidents_controller.rb
- app/controllers/supervisor_reports_controller.rb
- app/models/incident_report.rb
- app/models/injured_passenger.rb
- app/models/supervisor_report.rb
- app/views/incident_reports/_form.html.haml
- app/views/incident_reports/_show.haml
- app/views/incidents/show.pdf.prawn
- app/views/supervisor_reports/_form.haml
- app/views/supervisor_reports/_show.haml
- config/locales/en.yml
- coverage/.last_run.json
- db/migrate/20180307213145_add_incident_report_id_to_injured_passengers.rb
- db/schema.rb
- spec/factories/incident_reports.rb
- spec/factories/injured_passengers.rb
- spec/factories/supervisor_reports.rb
- spec/system/staff/viewing_incidents_spec.rb
- spec/system/supervisors/special_supervisor_report_fields_spec.rb
Requested by Carolyn, Tom, and Liza. Closes #126.
> Move injured passengers to incident report

- app/models/incident_report.rb
- app/views/incident_reports/_form.html.haml
- app/views/incident_reports/_show.haml
- config/locales/en.yml
- coverage/.last_run.json
- db/migrate/20180313231303_add_zip_to_incident_reports.rb
- db/schema.rb
- spec/factories/incident_reports.rb
- spec/spec_helper.rb
- spec/system/drivers/creating_incidents_spec.rb
Needed for claims integration (#127).
Closes #135.
> Add ZIP code to incident reports

- app/views/incident_reports/_form.html.haml
Closes https://github.com/umts/incidents/issues/134
> Move prompts

- app/controllers/incident_reports_controller.rb
- app/controllers/supervisor_reports_controller.rb
- coverage/.last_run.json
- spec/system/drivers/editing_incidents_spec.rb
- spec/system/supervisors/editing_incidents_spec.rb
- spec/system/supervisors/editing_supervisor_reports_spec.rb
Closes https://github.com/umts/incidents/issues/149. Having trouble with running full rspec? Sometimes it says 6 tests are failing, other times more. Sometimes less. No idea what's going on.
> Errors on delete

- spec/controllers/supervisor_reports_controller_spec.rb
> Small changes to make test pass

- app/assets/javascripts/incidents/batch_export.coffee
> Empty batch export

- Gemfile.lock
- coverage/.last_run.json
CVE-2018-16468
(I don't know why the coverage went up, but...It did.)
> Bumped loofah

- .gitignore
- .rubocop.yml
- spec/spec_helper.rb
Also did some other tidying in the spec_helper. Closes #177
> Specify a downloads directory for Chrome

- app/views/layouts/application.html.haml
- spec/spec_helper.rb
- spec/system/drivers/editing_incidents_spec.rb
- spec/system/drivers/special_incident_fields_spec.rb
- spec/system/staff/adding_users_spec.rb
- spec/system/staff/creating_incidents_spec.rb
- spec/system/staff/viewing_users_spec.rb
- spec/system/supervisors/editing_supervisor_reports_spec.rb
- spec/system/supervisors/special_supervisor_report_fields_spec.rb
Closes #156. Made the tests smaller by adding context and whatnot. In general, we needed to increase the `default_max_wait_time` as well as removing js.
> Test fixes

- config/deploy/production.rb
> Change ENV hash

- app/models/incident.rb
Addresses #180.
We'll leave this in place for a while and let Liza report on the results. Approach approved by Liza.
> Use ISO8601 datetime for claims integration

- app/views/incidents/by_date.haml
> Year navigation in month mode

- config/initializers/devise.rb
Temporary fix for #192 requested by Dave K.
> Extend timeout

- app/assets/javascripts/incident_reports/staff_reviews.coffee
- app/assets/javascripts/incidents/batch_export.coffee
- package.json
- yarn.lock
From 3.2 to 3.4
Also changed a few things that are deprecated now. Although jQuery says they don't imagine they'll be removed any time soon, it was a pretty easy change.
> Jquery upgrade

- coverage/.last_run.json
- spec/factories/supervisor_reports.rb
- spec/system/drivers/creating_incidents_spec.rb
- spec/system/drivers/editing_incidents_spec.rb
- spec/system/drivers/special_incident_fields_spec.rb
> This commit fixes the failing test 

- README.md
- db/schema.rb
- db/seeds.rb
`rails db:seed` was failing because PaperTrail's `whodunnit` method was being set incorrectly.
Also logging into the Rails server is confusing at the moment so I added an extra test user with set values that I will put in the Readme to make setup easier.
Lastly, I put everything in a module to appease Rubocop.
> Fix seeds error and create known test user

- app/controllers/incidents_controller.rb
- app/models/incident.rb
This PR should close issue #254.
> Updated Claims xml

- config/database.yml.example
- db/schema.rb
([utf8 is badly-named garbage](https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434))
> Use utfmb4 for tables by default

- coverage/.last_run.json
- spec/factories/incident_reports.rb
- spec/factories/incidents.rb
- spec/factories/injured_passengers.rb
- spec/factories/supervisor_reports.rb
- spec/factories/users.rb
- spec/factories/witnesses.rb
- spec/system/supervisors/special_supervisor_report_fields_spec.rb
Not entirely, but most of the stuff that changes view state. I also trimmed down `special_supervisor_report_fields_spec.rb` to use more factory traits and less `update!`ing the supervisor report. Closes #216
I ran that one spec file 100 times and got no failures.
I also got rid of static fields in factories while I was there.
> Removed quite a bit of randomness from factories

- coverage/.last_run.json
- spec/spec_helper.rb
- spec/system/access_control_spec.rb
- spec/system/drivers/listing_incidents_spec.rb
- spec/system/drivers/logging_in_spec.rb
- spec/system/drivers/printing_incidents_spec.rb
- spec/system/drivers/special_incident_fields_spec.rb
- spec/system/password_change_spec.rb
- spec/system/staff/adding_users_spec.rb
- spec/system/staff/creating_incidents_spec.rb
- spec/system/staff/deleting_incidents_spec.rb
- spec/system/staff/deleting_users_spec.rb
- spec/system/staff/editing_users_spec.rb
- spec/system/staff/logging_in_spec.rb
- spec/system/staff/reviewing_incidents_spec.rb
- spec/system/staff/viewing_incident_report_history_spec.rb
- spec/system/staff/viewing_incident_xml_spec.rb
- spec/system/staff/viewing_incidents_spec.rb
- spec/system/staff/viewing_users_spec.rb
- spec/system/supervisors/creating_incidents_spec.rb
- spec/system/supervisors/editing_incidents_spec.rb
- spec/system/supervisors/editing_supervisor_reports_spec.rb
- spec/system/supervisors/listing_incidents_spec.rb
- spec/system/supervisors/logging_in_spec.rb
- spec/system/supervisors/special_supervisor_report_fields_spec.rb
This is a PR into @jforgue's #253 as penance for making, like, 50 "you don't need this" comments.
> Use selenium even less

- app/views/incident_reports/_form.html.haml
Closes issue #175. This seemed like an easy way to fix this issue.
> Passenger checkbox fix 

- app/views/incident_reports/_form.html.haml
closes #203. I made the remaining fields viewable by both driver and supervisor.
> Make requested fields viewable by both driver and supervisor 

- app/views/incident_reports/_form.html.haml
Reverts umts/incidents#268
I mistakenly merged this before hearing back from an email. This change is no longer wanted.
> Revert "Make requested fields viewable by both driver and supervisor "

- Capfile
- Gemfile.lock
- config/deploy/production.rb
Also some config cleanup. This should take care or the deprecation warnings from Bundler
> Updated capistrano-bundler

- app/models/supervisor_report.rb
- app/views/incidents/show.pdf.prawn
- app/views/supervisor_reports/_form.haml
- app/views/supervisor_reports/_show.haml
- db/migrate/20200714214551_add_employee_representative_notified_at_to_supervisor_reports.rb
- db/migrate/20200714221544_add_employee_representative_arrived_at_to_supervisor_reports.rb
- db/migrate/20200715141905_change_column_name.rb
- db/schema.rb
- spec/factories/supervisor_reports.rb
closes #206 . This PR does not address the new issue 270 that branched from 206.  
Bellow is the Edit page
PDf 
Show page
> added requested fields to supervisor report

- config/deploy.rb
> added linked directory

- app/models/incident.rb
It was requested to add the route number to the claims xml.
> Add new field to claims xml

- app/controllers/application_controller.rb
- config/initializers/new_framework_defaults_5_2.rb
Safe to toggle all of these on, I think.
> Switch on Rails 5.2 defaults

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- lib/capistrano/tasks/sidekiq.rake
Finishes the work done in #291, the last of my half of #289.
Decided to go with the capistrano-sidekiq gem. We don't use it on umaps-rails for...historical reasons, but this seems to work fine.
Also, updated Sidekiq (no idea why I didn't go with 6.1 before).
> Hook up capistrano-sidekiq

- .travis.yml
Also:
* Use the newest LTS nodeJS
* Tell bundler to use "deplyment" mode
> Cache gems with bundler

- app/assets/javascripts/latlong_map.coffee
> Checks for presence instead of length 

- app/views/incident_reports/_form.html.haml
> Add example text to run field

- app/views/incidents/_incident.xml.haml
> Fix Hastus `ai_preventability` field mismatch

- Gemfile
- Gemfile.lock
- config/environments/production.rb
> Switch from uglifier to terser

- Gemfile
- Gemfile.lock
- config/deploy.rb
> Remove most version pins in Gemfile

- .github/workflows/ci.yml
> Indentation error on PR actions config
